### ISSUE TITLE
docker-compose, kapacitor paths dont has mounted

### ISSUE THREAD

**Issue by gebv** [influxdata/TICK-docker#10]
``` yml
version: "2"
services:
  influxdb:
    image: influxdb:0.13
    volumes:
        - ./state/influxdb/data:/var/lib/influxdb
        - ./state/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
        - "8083:8083"
        - "8086:8086"
  kapacitor:
    image: kapacitor:0.13
#    environment:
#        KAPACITOR_HOSTNAME: kapacitor
#        KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    volumes:
      - ./state/kapacitor/data:/var/lib/kapacitor
      - ./state/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    ports:
        - "9092:9092"
```

Folder `state/kapacitor/data` is empty. Does not contain at least `kapacitor.db`.
But `state/influxdb/data` it is ok.
```
.
├── data
│   └── _internal
│       └── monitor
├── meta
│   └── meta.db
└── wal
    └── _internal
        └── monitor
```

Config also don't has mounted.
```
volumes:
    - ./state/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
```

What's going on?
