### ISSUE TITLE
How can you make a backup of a database with TICK-docker?

### ISSUE THREAD

**Issue by jadster** [influxdata/TICK-docker#33]
When running influxdb as a standalone service (e.g. via `brew install influxdb`on Mac), I can easily make backups of any database using the command 

`influxd backup -database <database-name> <path-to-save-backup-files>`

How can I make this command work when influxdb is running in the docker?
Does it have to work with remote backups as described here:
`https://docs.influxdata.com/influxdb/v1.3/administration/backup_and_restore/#remote-backups`?

I can't get it to work. I suspect the influxdb.conf would have to be setup as indicated in the link above, but i don't understand how that can be accomplished when influxdb is started in docker with TICK-docker.

**Comment by jadster** [comment]
I think I figured out one way to do it. I need to enter into `docker exec` CLI.

To keep it simple I used the Mac App "Kitematic" that comes with the official Mac Docker installation.
Select the running influxdb container and hit the "exec" button at the top => a Terminal window opens up.

Then I can use the same command as with a native brew installation:

influxd backup -database <database-name> <path-to-save-backup-files>

In this case I have to use the path `/var/lib/influxdb/backups/<database-name>` because this is mapped to `~/TICK-docker/1.3/data/influxdb/backups/<database-name>` on my Mac file system.

---

I'd prefer getting the remote backup to work. I've tried changing the influxdb block of docker-compose.yml to this:
```
  influxdb:
    image: influxdb:1.3.5
    environment:
      INFLUXDB_BIND_ADDRESS: "127.0.0.1:8088"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8088:8088"
```

But then running e.g.

`influxd backup -database chronograf -host 127.0.0.1:8088 /tmp/mysnapshot`

(with a native influxdb installation installed (via brew))

I still get errors:
```
2017/12/09 02:03:34 backup failed: EOF
backup: EOF
```
